server:
  port: 2030
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
      url: jdbc:mysql://localhost:3306/olxmaster
      username: root
      password: root
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true