server:
  port: 2040
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/olxadvertise
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #security:
    #user:
     # name: Zensar
     # password: Zensar@123
